/* This file is generated by zits. Do not edit manually */


/** List of all Link kinds handled by this Zome */
export enum AgentDirectoryLinkType {
	Agent = 'Agent',
}
export enum AgentDirectoryUnitEnum {
	Stub = 'Stub',
}
